version: '3.8'  

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=LDB;Username=postgres;Password=root;
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy  
    

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=LDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    container_name: psql
    ports:
      - "5432:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d LDB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s  